### ISSUE TITLE
chap1

### ISSUE THREAD

**Issue by seiya8** [hrdakr/nlp100#2]
https://github.com/hrdakr/nlp100/blob/9b564404a9c4c2747f0864fca28df09ef0e80d50/chap1.py#L12-L19
for文で（インデックスを回すのではなく）文字列から文字をそのまま取ってくる方がシンプルに書けると思う
zipを使えば、2つの文字列から同時に取り出せる
```py
for s, t in zip(text1, text2):
```
みたいに

**Comment by seiya8** [comment]
https://github.com/hrdakr/nlp100/blob/9b564404a9c4c2747f0864fca28df09ef0e80d50/chap1.py#L23-L24
は `.replace(',', '').replace('.', '')`みたいにした方が良い

**Comment by seiya8** [comment]
https://github.com/hrdakr/nlp100/blob/9b564404a9c4c2747f0864fca28df09ef0e80d50/chap1.py#L26-L28
リスト内包表記で良いのでは

**Comment by seiya8** [comment]
https://github.com/hrdakr/nlp100/blob/9b564404a9c4c2747f0864fca28df09ef0e80d50/chap1.py#L38
は、enumerate文を使った方が見やすい。`for i, word in enumerate(words04):`

https://github.com/hrdakr/nlp100/blob/9b564404a9c4c2747f0864fca28df09ef0e80d50/chap1.py#L42
：冗長。`z.append(words04[i][:2])`でOK

https://github.com/hrdakr/nlp100/blob/9b564404a9c4c2747f0864fca28df09ef0e80d50/chap1.py#L45
ここでもう1回同じfor文回すなら、最初のfor文でもう辞書作っちゃえば良いのでは。

https://github.com/hrdakr/nlp100/blob/9b564404a9c4c2747f0864fca28df09ef0e80d50/chap1.py#L46
`data[z[i]] = i+1`でよい

**Comment by hrdakr** [comment]
最後の46行目の話があんまりわかんなかったんだけど
https://github.com/hrdakr/nlp100/blob/46ef143cf165b1c7a9c878e4e415af75773a989f/chap1.py#L44-L47
を
`data[z[i]] = i+1`
って言うのは
`data={}`
`for i in range(len(words04)):`
`           data[z[i]] = i+1`
`print(data)`
ってこと？

**Comment by seiya8** [comment]
それでも良いし、内包表記で
```py
{z[i]: i+1 for i in range(len(words04))}
```
でも

**Comment by hrdakr** [comment]
なるほど

**Comment by hrdakr** [comment]
これって書き直して更新するのがいいのかね？
それとも別のpyファイルを作って更新していく方が、過程が見えて勉強方法として適切かね？

**Comment by seiya8** [comment]
書き直して更新で良いのでは　コミット履歴が過程だし
あと問題ごとにpyファイルは分けた方が良いと思うけど

**Comment by hrdakr** [comment]
なるほど　やってみる

**Comment by seiya8** [comment]
https://github.com/hrdakr/nlp100/blob/a02d51ff95bf0d646fde30908515a99d296dac06/chap1/c1_q07.py#L5-L9
問題とやっていることが違う　関数を実装せよって書いてある
あと %s はC言語的な書き方なので、f-stringを使った方が良い

**Comment by seiya8** [comment]
https://github.com/hrdakr/nlp100/blob/a02d51ff95bf0d646fde30908515a99d296dac06/chap1/c1_q08.py#L16-L18
n_gramを使う必要はない
```
for letter in sentence:
```
でsentenceから1文字ずつ取り出される

**Comment by seiya8** [comment]
https://github.com/hrdakr/nlp100/blob/a02d51ff95bf0d646fde30908515a99d296dac06/chap1/c1_q08.py#L20
これは個人的意見だけど`if 97 <= n <= 122`の方がわかりやすいと思った

1行で書いた可読性0のコード:
```py
''.join(map(lambda x: chr(219-ord(x)) if 97 <= ord(x) <= 122 else x, input("文字列を入力")))
```

**Comment by seiya8** [comment]
https://github.com/hrdakr/nlp100/blob/5548ef09680d97ab75d4a6fa8fe9216b6f469723/chap1/c1_q09.py#L14-L17
- 配列への追加は `x.append(word)`, `x.append(y)`の方が良い
- `word[n-1]` は `word[-1]` で良い
